name: Build Resume PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FILE: cv.tex  # Ensure your main LaTeX file is named 'cv.tex'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{ env.FILE }}
          latexmk_shell_escape: true

      - name: Move Compiled PDF to Artifacts
        run: |
          mkdir -p github_artifacts
          mv cv.pdf github_artifacts/

      - name: Upload PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: github_artifacts/cv.pdf

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf
          path: github_deploy

      - name: Deploy to gh-pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
          enable_jekyll: true
